### PR TITLE
fix type error and wrong test

### PR DESCRIPTION
**Pull request by zardam**

### CODE REVIEW

**Comment by UweBonnes** [comment]
Fetch and try again. Does it now work as expected?

**Comment by zardam** [comment]
I closed the previous pull request as it was no more relevant. There is still a problem:

https://github.com/UweBonnes/blackmagic/blob/f0001b20667383cf5b4099c1d6b70431c3a05a3c/src/target/cortexm.c#L305-L310

Here, ap->designer is not initialized, so the check fails.

Even if I skip this check, there is a failure later (I got "Fault reading ID registers"). If I bypass cortexm_prepare function (by returning true as the first statement of this function), then I can probe a protected SAMD.

**Comment by UweBonnes** [comment]
Try again. Now cortexm_prepare reads the designer, if not yet already done.

**Comment by zardam** [comment]
Still not working. I think that you should not try to stop the target in the case of a SAMD because it locks it somehow, and everything fails after this.

I don't know if it is a problem to try to read the pidr earlier, and do nothing in case of a SAMD. By doing this, I can probe the SAMD, either protected or unprotected.

I have updated the pull request this way. It is working for the SAMD, but I don't know if reading the pidr earlier is harmless for other targets.

**Comment by UweBonnes** [comment]
Argh: The SAMD21 has an errata: 
"If a debugger has issued a DSU Cold-Plugging procedure and then
released the CPU from the resulting CPU Reset Extension, the CPU will
be held in CPU Reset Extension after any upcoming reset event."

That explains the locking you see. This contradicts withe the targets I have:
- Have the target running after scan. Otherwise it is easy to have the target hanging with need to unpower the target by some easy misshandling the debugger.
-

**Comment by kh90909** [comment]
I believe I've found the main issues preventing this from working. See #11. Doesn't fix the SAMD21 cold-plugging erratum, obviously, but it does allow detection of my SAMD51 when protected. (I've just submitted a pull request (#534) which adds SAMD51 / E5x support).

**Comment by UweBonnes** [comment]
Should work in git head,

**Pull request closed without merging**
