### PR TITLE
STM32F0 proper detection using DBGMCU_IDCODE_F0 regiter

### PR DESCRIPTION
**Pull request by aam335**
STM32F0 proper detection using DBGMCU_IDCODE_F0 regiter

### CODE REVIEW

**Comment by UweBonnes** [comment]
Please explain. The idcode is already read from the romtable:
...
ROM: Table BASE=0xe00ff000 SYSMEM=0x00000001, designer  20 Partno 440
...
Does that come out different for you? Please use hosted"blackmagic -t" and show the output

**Comment by aam335** [comment]
My stm32f042 has 0x440 in the romtable and is defined as STM32F05x and it has 0x445 in DBGMCU_IDCODE_F0 as described in 32.4.1 MCU device ID code for RM009. Without this patch, the FLASH size is incorrectly determined

**Comment by aam335** [comment]
original:
`INFO: Open USB 1d6b:0003 failed
Using 1d50:6018 DED6CED1 Black Sphere Technologies Black Magic Probe (SWLINK), (Firmware v1.6.1-629-g4ca8f78)
Remote is Black Magic Probe (SWLINK), (Firmware v1.6.1-629-g4ca8f78) v1.6.1-629-g4ca8f78
Running in Test Mode
Target voltage:  Volt
RESET_SEQ failed
AP   0: IDR=04770021 CFG=00000000 BASE=e00ff003 CSW=03000040
ROM: Table BASE=0xe00ff000 SYSMEM=0x00000001, designer  20 Partno 440
0 0xe000e000: Generic IP component - Cortex-M0 SCS (System Control Space) (PIDR = 0x04000bb008  DEVTYPE = 0x00 ARCHID = 0x0000)-> cortexm_probe
1 0xe0001000: Generic IP component - Cortex-M0 DWT (Data Watchpoint and Trace) (PIDR = 0x04000bb00a  DEVTYPE = 0x00 ARCHID = 0x0000)
2 0xe0002000: Generic IP component - Cortex-M0 BPU (Breakpoint Unit) (PIDR = 0x04000bb00b  DEVTYPE = 0x00 ARCHID = 0x0000)
ROM: Table END
***  1      STM32F04/F070x6 M0
Ram   Start: 0x20000000, length    0x5000
Flash Start: 0x08000000, length    0x8000, blocksize    0x400
`
patched:
`
INFO: Open USB 1d6b:0003 failed
Using 1d50:6018 DED6CED1 Black Sphere Technologies Black Magic Probe (SWLINK), (Firmware v1.6.1-629-g4ca8f78)
Remote is Black Magic Probe (SWLINK), (Firmware v1.6.1-629-g4ca8f78) v1.6.1-629-g4ca8f78
Running in Test Mode
Target voltage:  Volt
RESET_SEQ failed
AP   0: IDR=04770021 CFG=00000000 BASE=e00ff003 CSW=03000040
ROM: Table BASE=0xe00ff000 SYSMEM=0x00000001, designer  20 Partno 440
0 0xe000e000: Generic IP component - Cortex-M0 SCS (System Control Space) (PIDR = 0x04000bb008  DEVTYPE = 0x00 ARCHID = 0x0000)-> cortexm_probe
1 0xe0001000: Generic IP component - Cortex-M0 DWT (Data Watchpoint and Trace) (PIDR = 0x04000bb00a  DEVTYPE = 0x00 ARCHID = 0x0000)
2 0xe0002000: Generic IP component - Cortex-M0 BPU (Breakpoint Unit) (PIDR = 0x04000bb00b  DEVTYPE = 0x00 ARCHID = 0x0000)
ROM: Table END
***  1      STM32F04/F070x6 M0
Ram   Start: 0x20000000, length    0x5000
Flash Start: 0x08000000, length    0x8000, blocksize    0x400
`

**Comment by UweBonnes** [comment]
Your second last comment makes sense, your last comment with the log does not, as for me both outputs are identical . Checking for AP_DESIGNER_STM was already done in cortexm.c, so drop it. Probably checking for a M0 core would be more safe, as maybe some F0 have a different romtable partno. I implemented as cpuid branch here. Please try and report back. And open an issue on blacksphere.

**Comment by aam335** [comment]
(t->cpuid & CPUID_CORE_MASK) == CORTEX_M0 method works fine!
...
ROM: Table END
***  1      STM32F04/F070x6 M0
Ram   Start: 0x20000000, length    0x5000
Flash Start: 0x08000000, length    0x8000, blocksize    0x400

**Comment by aam335** [comment]
> as for me both outputs are identical
Missed, now corrected

**Comment by UweBonnes** [comment]
Implemented in git head.

**Pull request closed without merging**
