### PR TITLE
Scan for BMPs on Windwos

### PR DESCRIPTION
**Pull request by sidprice**
This patch fixes the issue where hosted does not find BMPs under Windows. The patch contains a new method that scans the Windows registry to find connected BMPs.

### CODE REVIEW

**Comment by UweBonnes** [comment]
I think this is the wrong approch. Let finddebuggers() as is. At the end of finddebugger,  if one probe is selected, VID/PID and serial  number are returned. If it is a BPM, later serial_xxx() is called with VID/PID and serial  number. As I understand you, with VID/PID and serial number you can retrieve the COMx interface from the registry. serial_win.c now has all the information to open and handle the BMP.

**Comment by sidprice** [comment]
Sorry, I don't understand this comment. The original finddebuggers does not "see" BMPs on Windows so at the end of the call it has found nothing.

Please explain what I am missing here, thanks.

**Comment by UweBonnes** [comment]
Finddebuggers is meant to scan the USB bus for BMP/ST-Link/CMSIS-DAP/JLINK adapter by their VID/PID or the CMSIS string in vendor/product id. finddebuggers does this with libusb and to make a device known to libusb on windows, Zadig "USB driver installation made easy" must be used. 
Beside BMP, all other supported probes also need libusb access to later use the device. Is I now understand, giving the BMP to Zadig would inhibit COMx access. So finddebuggers() on windows must take another approach. I do not yet now how.

**Comment by sidprice** [comment]
Agreed, and that is what I wrote in my added function.

**Pull request closed without merging**
